# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5fd850e22178796af7c25995b6c36a061b3dab35e8b09331d40c7d849481cfb3e86c5136d2503af95127383c50fa0221d542a72f35e1ad92008b606dfde58d4

test:
  secret_key_base: 406d557c5fb81644e567db762a6ae0ade122550619afeb865f61381f9afdc833827e48753cbc75d3986031f85d4a455e1c251d1ed64b475d694c9b88d178fcad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
